export type PreviewMenuSlot='start'|'sea'|'land'|'green'|'finish'
export interface PreviewMenuCandidate{name:string;description:string;indicator:string}
export interface PreviewMenuCourse{slot:PreviewMenuSlot;section:string;selectedCandidate:PreviewMenuCandidate;alternateCandidates:[PreviewMenuCandidate,PreviewMenuCandidate];locked:boolean;customOverride?:string}
export const PREVIEW_MENU_COURSES:readonly PreviewMenuCourse[]=[
 {slot:'start',section:'To Begin',selectedCandidate:{name:'Heirloom Tomato & Labneh',description:'Mint, toasted seeds, and good olive oil.',indicator:'Serves the whole table'},alternateCandidates:[{name:'Charred Eggplant Fatteh',description:'Tahini, crisp pita, and sumac.',indicator:'Vegetarian'},{name:'Citrus Fennel Salad',description:'Orange blossom and toasted pistachio.',indicator:'Bright'}],locked:false},
 {slot:'sea',section:'From the Sea',selectedCandidate:{name:'Whole Grilled Sea Bass',description:'Charred lemon, herbs, and a bright green sauce.',indicator:'Pescatarian'},alternateCandidates:[{name:'Seared Scallops & Corn',description:'Brown butter and preserved lemon.',indicator:'Shellfish'},{name:'Sumac Salmon',description:'Herb rice and cucumber.',indicator:'Pescatarian'}],locked:false},
 {slot:'land',section:'From the Land',selectedCandidate:{name:'Lamb Shoulder with Freekeh',description:'Slow-cooked lamb, smoky grains, and pan jus.',indicator:'Signature'},alternateCandidates:[{name:'Braised Beef Short Rib',description:'Date molasses and silky onions.',indicator:'Rich'},{name:'Roast Chicken with Za’atar',description:'Lemon jus and crisp potatoes.',indicator:'Table favorite'}],locked:false},
 {slot:'green',section:'From the Garden',selectedCandidate:{name:'Roasted Cauliflower & Tahini',description:'Herbs, currants, and toasted sesame.',indicator:'Vegan'},alternateCandidates:[{name:'Braised Leeks',description:'Mustard, herbs, and soft egg.',indicator:'Vegetarian'},{name:'Stuffed Summer Squash',description:'Tomato, freekeh, and mint.',indicator:'Plant-forward'}],locked:false},
 {slot:'finish',section:'To Finish',selectedCandidate:{name:'Burnt Basque Cheesecake',description:'Dark caramel top with a soft, creamy center.',indicator:'To share'},alternateCandidates:[{name:'Orange Blossom Panna Cotta',description:'Apricot and pistachio.',indicator:'Silky'},{name:'Dark Chocolate Tahini Tart',description:'Sea salt and sesame brittle.',indicator:'Rich'}],locked:false},
] as const
export const PREVIEW_MENU_DISHES=PREVIEW_MENU_COURSES.map(course=>({...course.selectedCandidate,section:course.section}))
