export type PreviewMenuSlot='starter'|'main'|'side'|'dessert'
export interface PreviewMenuCandidate{name:string;description:string;indicator:string}
export interface PreviewMenuCourse{slot:PreviewMenuSlot;section:string;selectedCandidate:PreviewMenuCandidate;alternateCandidates:[PreviewMenuCandidate,PreviewMenuCandidate];locked:boolean;customOverride?:string}
export const PREVIEW_MENU_COURSES:readonly PreviewMenuCourse[]=[
 {slot:'starter',section:'To Start',selectedCandidate:{name:'Heirloom Tomato & Labneh',description:'Mint, toasted seeds, and good olive oil.',indicator:'Serves the whole table'},alternateCandidates:[{name:'Charred Eggplant Fatteh',description:'Tahini, crisp pita, and sumac.',indicator:'Vegetarian'},{name:'Citrus Fennel Salad',description:'Orange blossom and toasted pistachio.',indicator:'Bright'}],locked:false},
 {slot:'main',section:'Mains',selectedCandidate:{name:'Lamb Shoulder with Freekeh',description:'Slow-cooked lamb, smoky grains, and pan jus.',indicator:'Signature'},alternateCandidates:[{name:'Whole Grilled Sea Bass',description:'Charred lemon, herbs, and a bright sauce.',indicator:'Pescatarian'},{name:'Roast Chicken with Za’atar',description:'Lemon jus and crisp potatoes.',indicator:'Table favorite'}],locked:false},
 {slot:'side',section:'On the Side',selectedCandidate:{name:'Roasted Cauliflower & Tahini',description:'Herbs, currants, and toasted sesame.',indicator:'Vegan'},alternateCandidates:[{name:'Braised Leeks',description:'Mustard, herbs, and soft egg.',indicator:'Vegetarian'},{name:'Stuffed Summer Squash',description:'Tomato, freekeh, and mint.',indicator:'Plant-forward'}],locked:false},
 {slot:'dessert',section:'To Finish',selectedCandidate:{name:'Burnt Basque Cheesecake',description:'Dark caramel top with a soft, creamy center.',indicator:'To share'},alternateCandidates:[{name:'Orange Blossom Panna Cotta',description:'Apricot and pistachio.',indicator:'Silky'},{name:'Dark Chocolate Tahini Tart',description:'Sea salt and sesame brittle.',indicator:'Rich'}],locked:false},
] as const
export const PREVIEW_MENU_DISHES=PREVIEW_MENU_COURSES.map(course=>({...course.selectedCandidate,section:course.section}))
