'use client'
import {KeyboardEvent,useState} from 'react'
import {useRouter} from 'next/navigation'
import {INGREDIENT_PRESETS} from '@/lib/ingredient-presets'
import {PREVIEW_MENU_DISHES} from './menu-fixtures'
import {sv2Display,sv2Sans} from './fonts'
import {PreviewBottomNav} from './PreviewBottomNav'
import {updatePreviewSession} from './preview-session'
const signatureOptions=PREVIEW_MENU_DISHES.map(d=>d.name)
const pantryOptions=Object.values(INGREDIENT_PRESETS).flat().slice(0,18)
function Editor({title,options}:{title:string;options:string[]}){const[selected,setSelected]=useState<string[]>(options.slice(0,3)),[custom,setCustom]=useState<string[]>([]),[draft,setDraft]=useState('');function toggle(value:string){setSelected(previous=>previous.includes(value)?previous.filter(item=>item!==value):[...previous,value])}function add(){const value=draft.trim();if(!value||[...options,...custom].some(item=>item.toLowerCase()===value.toLowerCase()))return;setCustom(previous=>[...previous,value]);setSelected(previous=>[...previous,value]);setDraft('')}function key(event:KeyboardEvent<HTMLInputElement>){if(event.key==='Enter'){event.preventDefault();add()}}return <section className="sv2-inventory-editor"><h2>{title}</h2><div className="sv2-inventory-chips">{options.map(value=><button type="button" aria-pressed={selected.includes(value)} key={value} onClick={()=>toggle(value)}>{value}</button>)}{custom.map(value=><span key={value}>{value}<button type="button" aria-label={`Remove ${value}`} onClick={()=>{setCustom(previous=>previous.filter(item=>item!==value));setSelected(previous=>previous.filter(item=>item!==value))}}>×</button></span>)}</div><div className="sv2-inventory-add"><input aria-label={`Add custom ${title.toLowerCase()} item`} value={draft} onChange={event=>setDraft(event.target.value)} onKeyDown={key} placeholder="Add your own"/><button type="button" onClick={add}>ADD</button></div></section>}
export function MyKitchenPreview({eventContext=false}:{eventContext?:boolean}){const router=useRouter();function save(){updatePreviewSession({inventoryUpdated:true,role:eventContext?'host':undefined});router.push(eventContext?'/design-preview/events/demo/menu':'/design-preview/events')}return <div className={`sv2-root sv2-device-page sv2-app-page ${sv2Display.variable} ${sv2Sans.variable}`}><main className="sv2-device-shell sv2-app-shell sv2-kitchen-shell"><header className="sv2-menu-topline"><p>Sofra.</p></header>{eventContext&&<p className="sv2-event-kicker">LAYLA&apos;S SOFRA · HOST INVENTORY</p>}<h1>{eventContext?'Inventory':'My Kitchen'}</h1><Editor title="SIGNATURE DISHES" options={signatureOptions}/><Editor title="PANTRY" options={pantryOptions}/><button className="sv2-inventory-save" type="button" onClick={save}>UPDATE INVENTORY</button><PreviewBottomNav current="events"/></main></div>}
