'use client'
import {KeyboardEvent,useState} from 'react'
import {INGREDIENT_PRESETS} from '@/lib/ingredient-presets'
import {PREVIEW_MENU_DISHES} from './menu-fixtures'
import {sv2Display,sv2Sans} from './fonts'
import {PreviewBottomNav} from './PreviewBottomNav'
const signatureOptions=PREVIEW_MENU_DISHES.map(d=>d.name)
const pantryOptions=Object.values(INGREDIENT_PRESETS).flat().slice(0,18)
function Editor({title,options}:{title:string;options:string[]}){const [selected,setSelected]=useState<string[]>(options.slice(0,3)),[custom,setCustom]=useState<string[]>([]),[draft,setDraft]=useState('');function toggle(v:string){setSelected(p=>p.includes(v)?p.filter(x=>x!==v):[...p,v])}function add(){const value=draft.trim();if(!value||[...options,...custom].some(x=>x.toLowerCase()===value.toLowerCase()))return;setCustom(p=>[...p,value]);setSelected(p=>[...p,value]);setDraft('')}function key(e:KeyboardEvent<HTMLInputElement>){if(e.key==='Enter'){e.preventDefault();add()}}return <section className="sv2-inventory-editor"><h2>{title}</h2><div className="sv2-inventory-chips">{options.map(v=><button type="button" aria-pressed={selected.includes(v)} key={v} onClick={()=>toggle(v)}>{v}</button>)}{custom.map(v=><span key={v}>{v}<button type="button" aria-label={`Remove ${v}`} onClick={()=>{setCustom(p=>p.filter(x=>x!==v));setSelected(p=>p.filter(x=>x!==v))}}>×</button></span>)}</div><div className="sv2-inventory-add"><input aria-label={`Add custom ${title.toLowerCase()} item`} value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={key} placeholder="Add your own"/><button type="button" onClick={add}>ADD</button></div></section>}
export function MyKitchenPreview({eventContext=false}:{eventContext?:boolean}){const [saved,setSaved]=useState(false);return <div className={`sv2-root sv2-device-page sv2-app-page ${sv2Display.variable} ${sv2Sans.variable}`}><main className="sv2-device-shell sv2-app-shell sv2-kitchen-shell"><header className="sv2-menu-topline"><p>Sofra.</p></header>{eventContext&&<p className="sv2-event-kicker">LAYLA&apos;S SOFRA · HOST INVENTORY</p>}<h1>{eventContext?'Inventory':'My Kitchen'}</h1><Editor title="SIGNATURE DISHES" options={signatureOptions}/><Editor title="PANTRY" options={pantryOptions}/><button className="sv2-inventory-save" type="button" onClick={()=>setSaved(true)}>UPDATE INVENTORY</button>{saved&&<p className="sv2-inventory-saved" role="status">Inventory updated in this preview.</p>}<PreviewBottomNav current="events"/></main></div>}
