'use client'
import {KeyboardEvent,useState} from 'react'
import {useRouter} from 'next/navigation'
import {DISH_PRESETS} from '@/lib/dish-presets'
import {INGREDIENT_CATEGORIES,INGREDIENT_PRESETS} from '@/lib/ingredient-presets'
import {PANTRY_TAG_GROUPS,SIGNATURE_TAG_GROUPS,TagGroup} from '@/lib/kitchen-tags'
import {formatTagLabel} from '@/lib/tag-format'
import {sv2Display,sv2Sans} from './fonts'
import {PreviewBottomNav} from './PreviewBottomNav'
import {PreviewInventoryItem,readPreviewSession,updatePreviewSession} from './preview-session'
type EditorKind='signature'|'pantry'
function MetadataEditor({name,groups,onCancel,onConfirm}:{name:string;groups:readonly TagGroup[];onCancel:()=>void;onConfirm:(item:PreviewInventoryItem)=>void}){const[tags,setTags]=useState<string[]>([]);function toggle(group:TagGroup,tag:string){setTags(current=>group.label==='Role'?[...current.filter(value=>!group.tags.includes(value)),tag]:current.includes(tag)?current.filter(value=>value!==tag):[...current,tag])}return <section className="sv2-metadata-editor" aria-label={`Tag ${name}`}><header><p>NEW ITEM</p><h3>{name}</h3></header>{groups.map(group=><fieldset key={group.label}><legend>{group.label}</legend><div>{group.tags.map(tag=><button type="button" key={tag} aria-pressed={tags.includes(tag)} onClick={()=>toggle(group,tag)}>{formatTagLabel(tag)}</button>)}</div></fieldset>)}<footer><button type="button" onClick={onCancel}>CANCEL</button><button type="button" disabled={!tags.length} onClick={()=>onConfirm({name,tags})}>ADD TO INVENTORY</button></footer></section>}
function Editor({kind,title,options,groups,initial,onItemsChange}:{kind:EditorKind;title:string;options:string[];groups:readonly TagGroup[];initial:PreviewInventoryItem[];onItemsChange:(items:PreviewInventoryItem[])=>void}){const[selected,setSelected]=useState<string[]>(initial.map(item=>item.name)),[custom,setCustom]=useState<PreviewInventoryItem[]>(initial.filter(item=>!options.includes(item.name))),[draft,setDraft]=useState(''),[pending,setPending]=useState('');function commit(items:PreviewInventoryItem[],selection:string[]){setCustom(items.filter(item=>!options.includes(item.name)));setSelected(selection);onItemsChange([...selection.filter(name=>!items.some(item=>item.name===name)).map(name=>({name,tags:[]})),...items])}function toggle(value:string){const next=selected.includes(value)?selected.filter(item=>item!==value):[...selected,value];setSelected(next);onItemsChange([...next.map(name=>custom.find(item=>item.name===name)??{name,tags:[]})])}function begin(){const value=draft.trim();if(!value||options.some(item=>item.toLowerCase()===value.toLowerCase())||custom.some(item=>item.name.toLowerCase()===value.toLowerCase()))return;setPending(value);setDraft('')}function key(event:KeyboardEvent<HTMLInputElement>){if(event.key==='Enter'){event.preventDefault();begin()}}return <section className={`sv2-inventory-editor sv2-inventory-editor-${kind}`}><h2>{title}</h2><div className="sv2-inventory-chips">{options.map(value=><button type="button" aria-pressed={selected.includes(value)} key={value} onClick={()=>toggle(value)}>{value}</button>)}{custom.map(item=><span key={item.name}>{item.name}<button type="button" aria-label={`Remove ${item.name}`} onClick={()=>commit(custom.filter(value=>value.name!==item.name),selected.filter(value=>value!==item.name))}>×</button></span>)}</div><div className="sv2-inventory-add"><input aria-label={`Add custom ${title.toLowerCase()} item`} value={draft} onChange={event=>setDraft(event.target.value)} onKeyDown={key} placeholder="Add your own"/><button className="sv2-inventory-add-button" type="button" onClick={begin}>ADD</button></div>{pending&&<MetadataEditor name={pending} groups={groups} onCancel={()=>setPending('')} onConfirm={item=>{const items=[...custom,item];commit(items,[...selected,item.name]);setPending('')}}/>}</section>}
export function MyKitchenPreview({eventContext=false}:{eventContext?:boolean}){const router=useRouter();const session=readPreviewSession();const[signatures,setSignatures]=useState<PreviewInventoryItem[]>(session.signatureInventory),[pantry,setPantry]=useState<PreviewInventoryItem[]>(session.pantryInventory);function save(){updatePreviewSession({inventoryUpdated:true,role:eventContext?'host':session.role,signatureInventory:signatures,pantryInventory:pantry});router.push(eventContext?'/design-preview/events/demo?role=host':'/design-preview/events')}const pantryOptions=INGREDIENT_CATEGORIES.flatMap(category=>INGREDIENT_PRESETS[category]);return <div className={`sv2-root sv2-device-page sv2-app-page ${sv2Display.variable} ${sv2Sans.variable}`}><main className="sv2-device-shell sv2-app-shell sv2-kitchen-shell"><header className="sv2-menu-topline"><p>Sofra.</p></header>{eventContext&&<p className="sv2-event-kicker">LAYLA&apos;S SOFRA · HOST INVENTORY</p>}<h1>{eventContext?'Inventory':'My Kitchen'}</h1><Editor kind="signature" title="SIGNATURE DISHES" options={DISH_PRESETS.map(preset=>preset.name)} groups={SIGNATURE_TAG_GROUPS} initial={signatures} onItemsChange={setSignatures}/><Editor kind="pantry" title="PANTRY" options={pantryOptions} groups={PANTRY_TAG_GROUPS} initial={pantry} onItemsChange={setPantry}/><button className="sv2-inventory-save" type="button" onClick={save}>UPDATE INVENTORY</button><PreviewBottomNav current="events"/></main></div>}
