'use client'
import {useRouter} from 'next/navigation'
import {useState} from 'react'
import {sv2Display,sv2Sans} from './fonts'
import {PREVIEW_EVENTS} from './events-fixtures'
import {PreviewBottomNav} from './PreviewBottomNav'
import {readPreviewSession,resetPreviewSession,updatePreviewSession} from './preview-session'
import {ThemeToggle} from './ThemeToggle'
export function ProfilePreview(){const router=useRouter();const session=readPreviewSession();const[photo,setPhoto]=useState<string|undefined>(session.profilePhoto);function select(file?:File){if(!file)return;const reader=new FileReader();reader.onload=()=>{const value=String(reader.result);setPhoto(value);updatePreviewSession({profilePhoto:value})};reader.readAsDataURL(file)}const name=session.name||'Alia',phone=session.phone||'+20 10 1234 5678';return <div className={`sv2-root sv2-device-page sv2-app-page ${sv2Display.variable} ${sv2Sans.variable}`}><main className="sv2-device-shell sv2-app-shell sv2-profile-shell"><header className="sv2-profile-topline"><p>Sofra.</p><ThemeToggle/></header><section className="sv2-profile-identity" aria-labelledby="sv2-profile-name"><label className="sv2-profile-photo" tabIndex={0}>{photo?<img src={photo} alt="Selected local profile preview"/>:<><span>{name.split(/\s+/).map(part=>part[0]).join('').slice(0,2).toUpperCase()}</span><small aria-hidden="true">📷</small></>}<span className="sv2-sr-only">Choose a profile photo</span><input aria-label="Choose a profile photo" type="file" accept="image/*" onChange={event=>select(event.target.files?.[0])}/></label><p className="sv2-profile-photo-helper">{photo?'Change photo':'Add profile photo'}</p><h1 id="sv2-profile-name">{name}</h1><p>{phone} · 4 Sofras since 2025</p></section><section className="sv2-profile-preferences"><h2>My preferences</h2><p>Vegetarian friendly · avoids nuts · bright and herbal · bravery 72</p></section><section className="sv2-profile-history"><h2>Your Sofras</h2><div>{PREVIEW_EVENTS.map(event=><article key={event.id}><span className="sv2-profile-history-icon">◇</span><div><h3>{event.title}</h3><p>{event.date} · {event.location}</p></div></article>)}</div></section><button className="sv2-profile-logout" type="button" onClick={()=>{resetPreviewSession();router.push('/design-preview')}}>LOG OUT</button><PreviewBottomNav current="profile"/></main></div>}
