import type { RecommendationPlan } from './pipeline'
import { RECOMMENDATION_CONFIG } from './config'

export type MenuCreationBrief={event:{guestCount:number;targetDishCount:number;missingDishCount:number};selectedSignatures:{name:string;role:string;mayBeRefined:boolean}[];gaps:{requestedRole:string;substantialRequired:boolean;culinaryGoal:string;underservedNeed:string[];proteinDirections:string[];flavorDirections:string[];avoid:string[]}[];availableIngredientsByCategory:{category:string;names:string[]}[];constraints:string[];purchaseRules:{maximumMissingPerDish:number;maximumCoreMissingPerDish:number;maximumUniqueMissingAcrossMenu:number}}

export function buildMenuCreationBrief(plan:RecommendationPlan):MenuCreationBrief{
  const grouped=new Map<string,string[]>();for(const x of plan.ingredients)grouped.set(x.category,[...(grouped.get(x.category)??[]),x.item.name])
  return{event:{guestCount:plan.guestCount,targetDishCount:plan.targetDishCount,missingDishCount:plan.gaps.length},selectedSignatures:plan.selected.map(x=>({name:x.signature.name,role:x.role,mayBeRefined:false})),gaps:plan.gaps.map(g=>({requestedRole:g.requestedRole,substantialRequired:g.substantialRequired,culinaryGoal:`Create one ${g.substantialRequired?'substantial ':''}${g.requestedRole} that complements the selected menu.`,underservedNeed:g.underservedDinerSummary.map(s=>s.replace(/^.*?:\s*/,'')),proteinDirections:g.proteinDirections,flavorDirections:g.flavorDirections,avoid:g.avoidRepetition})),availableIngredientsByCategory:Array.from(grouped,([category,names])=>({category,names})),constraints:plan.gaps[0]?.dietaryConstraints??[],purchaseRules:{maximumMissingPerDish:RECOMMENDATION_CONFIG.purchasing.majorMaximumMissing,maximumCoreMissingPerDish:RECOMMENDATION_CONFIG.purchasing.maximumCoreMissing,maximumUniqueMissingAcrossMenu:RECOMMENDATION_CONFIG.purchasing.maximumUniqueMissingPerMenu}}
}

export function buildCompactGapPrompt(brief:MenuCreationBrief):string{return `You are Sofra's culinary synthesis layer. Preserve selected signatures and create exactly ${brief.event.missingDishCount} generated dishes, one per declared gap. Return signatureRefinements as an empty array unless a selected signature explicitly allows refinement. Do not calculate or claim safety. Use canonical available ingredient names exactly. List every unavailable addition under missingIngredients. Keep names short and reasoning empty to fit the response limit. Return JSON only matching: {"signatureRefinements":[],"generatedDishes":[{"role":"starter|main|side|dessert|flex","finalName":"","usedAvailableIngredients":[""],"missingIngredients":[{"name":"","importance":"core|supporting|optional"}],"reasoning":""}]}. BRIEF=${JSON.stringify(brief)}`}
