import type { RecommendationPlan } from './pipeline'
import { RECOMMENDATION_CONFIG } from './config'

export type MenuCreationBrief={event:{guestCount:number;targetDishCount:number;missingDishCount:number};selectedSignatures:{name:string;role:string;mayBeRefined:boolean}[];gaps:{gapIndex:number;requestedRole:string;substantialRequired:boolean;targetDinerCount:number;targetDiners:{dinerIndex:number;needsSubstantialSafeDish:boolean;proteinNeed:string[];sensoryNeed:string[];dietaryConstraints:string[]}[];culinaryGoal:string;underservedNeed:string[];proteinDirections:string[];flavorDirections:string[];avoid:string[]}[];availableIngredientsByCategory:{category:string;names:string[]}[];constraints:string[];purchaseRules:{maximumMissingPerDish:number;maximumCoreMissingPerDish:number;maximumUniqueMissingAcrossMenu:number}}

export function buildMenuCreationBrief(plan:RecommendationPlan):MenuCreationBrief{
  const grouped=new Map<string,string[]>();for(const x of plan.ingredients)grouped.set(x.category,[...(grouped.get(x.category)??[]),x.item.name])
  return{event:{guestCount:plan.guestCount,targetDishCount:plan.targetDishCount,missingDishCount:plan.gaps.length},selectedSignatures:plan.selected.map(x=>({name:x.signature.name,role:x.role,mayBeRefined:false})),gaps:plan.gaps.map(g=>({gapIndex:g.gapIndex,requestedRole:g.requestedRole,substantialRequired:g.substantialRequired,targetDinerCount:g.targetDiners.length,targetDiners:g.targetDiners.map(t=>({dinerIndex:t.dinerIndex,needsSubstantialSafeDish:t.needsSubstantialSafeDish,proteinNeed:t.proteinNeed,sensoryNeed:t.flavorNeed,dietaryConstraints:t.dietaryConstraints})),culinaryGoal:`Create one ${g.substantialRequired?'substantial ':''}${g.requestedRole} that deterministically fits its target diners.`,underservedNeed:g.underservedDinerSummary.map(s=>s.replace(/^.*?:\s*/,'')),proteinDirections:g.proteinDirections,flavorDirections:g.flavorDirections,avoid:g.avoidRepetition})),availableIngredientsByCategory:Array.from(grouped,([category,names])=>({category,names})),constraints:Array.from(new Set(plan.gaps.flatMap(g=>g.dietaryConstraints))),purchaseRules:{maximumMissingPerDish:RECOMMENDATION_CONFIG.purchasing.majorMaximumMissing,maximumCoreMissingPerDish:RECOMMENDATION_CONFIG.purchasing.maximumCoreMissing,maximumUniqueMissingAcrossMenu:RECOMMENDATION_CONFIG.purchasing.maximumUniqueMissingPerMenu}}
}

export function chooseRepairGap(gaps:MenuCreationBrief['gaps'],dinerIndex:number|undefined,role:string){return(dinerIndex===undefined?undefined:gaps.find(g=>g.requestedRole===role&&g.targetDiners.some(t=>t.dinerIndex===dinerIndex)))??(dinerIndex===undefined?undefined:gaps.find(g=>g.targetDiners.some(t=>t.dinerIndex===dinerIndex)))??gaps.find(g=>g.requestedRole===role)}

export function buildCompactGapPrompt(brief:MenuCreationBrief):string{return `You are Sofra's culinary synthesis layer. Preserve selected signatures and create exactly ${brief.event.missingDishCount} generated dishes in gap order. Each dish must target only its gap's anonymous diners and return dish-specific canonical metadata; never copy the table-wide union. Do not claim safety: the validator decides. Use canonical available ingredient names exactly and list unavailable additions under missingIngredients. Return JSON only matching the supplied schema. Keep names short and reasoning empty. BRIEF=${JSON.stringify(brief)}`}
