import type { TasteProfile } from '@/lib/intel'
import type { PantryItem, Signature } from '@/lib/menu'
import { dishRoleByName, isDishRole } from '@/lib/dish-presets'
import { RECOMMENDATION_CONFIG, type DishRole } from './config'
import { calculateTargetDishCount, ingredientContextCeiling, requiredSatisfyingDishCount, requiredSubstantialDishCount, roleBlueprint, roleCeilings } from './planning'

export type Fit = { eligibility: 0 | 1; protein: number; flavor: number; adventurousness: number; q: number }
type Residual = { name: string; satisfying: number; substantial: number; value: number }
export type ScoredSignature = { signature: Signature; role: DishRole; score: number; base: number; underserved: number; diversity: number; fits: Fit[] }
export type GapDinerTarget={dinerIndex:number;needsSatisfyingDish:boolean;needsSubstantialSafeDish:boolean;proteinNeed:string[];flavorNeed:string[];dietaryConstraints:string[]}
export type MenuGap = { gapIndex:number;requestedRole: DishRole; substantialRequired: boolean; targetDiners:GapDinerTarget[]; underservedDinerSummary: string[]; dietaryConstraints: string[]; proteinDirections: string[]; flavorDirections: string[]; avoidRepetition: string[] }
export type IngredientDiagnostic = { item: PantryItem; category: string; relevance: number; redundancy: number; mmr: number }
export type RetrievalDiagnostics = { beforeThreshold:number; afterThreshold:number; afterCategoryCeilings:number; afterMmr:number; categoryBreakdown:Record<string,number> }
export type SignatureCandidateDiagnostic={name:string;role:DishRole;T_d:number;S_d:number;R_d:number;U_d:number;B_d:number;RoleNeed:number;D_d:number;M_d:number;baseScore:number;dynamicScore:number;selected:boolean;reason:string}
export type RecommendationPlan = { guestCount: number; targetDishCount: number; selected: ScoredSignature[]; residuals: Residual[]; gaps: MenuGap[]; ingredients: IngredientDiagnostic[]; contextCeiling: number; retrievalDiagnostics:RetrievalDiagnostics; signatureCandidates:SignatureCandidateDiagnostic[]; lockedCount:number; infeasibleDinerIndexes:number[];insufficientData: boolean }

const HARD_DIETS = new Set(['vegetarian','vegan','gluten-free','no dairy','no pork','kosher','pescatarian'])
const ALLERGY_WORDS = new Set(['nuts','shellfish','dairy','eggs','gluten','soy','sesame','mustard','celery','sulfites','lupin','molluscs'])
// Keep in sync with VOCAB in lib/recommendation/proposal.ts -- these are the
// dimensions dinerDishFit actually recognizes when scoring a dish's tags
// against a diner's stated preferences. Any value the LLM is legally allowed
// to emit (per VOCAB there) but that's missing here silently fails to match
// no matter how precisely the LLM targets a diner (e.g. 'acidic' and 'umami'
// were legal LLM output but absent from `flavor`, so a dish correctly tagged
// exactly to a diner's stated preference still scored as a non-match).
const GROUPS: Record<string, string[]> = { flavor:['savory','fresh','spicy','smoky','rich','bright','sweet','tangy','acidic','earthy','umami','mild','bitter','herbal'], texture:['crispy','creamy','crunchy','tender','silky','chewy','juicy','flaky','firm','soft'], technique:['grilled','roasted','fried','braised','raw','baked','steamed','boiled','seared','smoked','stewed','pickled'], protein:['beef','lamb','chicken','turkey','pork','duck','fish','shellfish','egg','dairy','legume','tofu','mushroom','grain','pasta','vegetable','fruit'], temperature:['hot','cold','room_temperature','chilled'], richness:['rich','fresh','light'] }
const lower = (xs: string[] = []) => xs.map(x => x.toLowerCase())
const clamp = (n: number) => Math.max(0, Math.min(1, n))
const jaccard = (a: string[], b: string[]) => { const A=new Set(a),B=new Set(b),u=new Set(a.concat(b)); return u.size?Array.from(A).filter(x=>B.has(x)).length/u.size:0 }
const group = (tags:string[], name:string) => Object.fromEntries(Object.entries(GROUPS).map(([k,v])=>[k,v.filter(x=>lower(tags).includes(x)||name.toLowerCase().includes(x))])) as Record<string,string[]>
const roleOf = (s: Signature): DishRole => lower(s.tags).find(isDishRole) as DishRole || dishRoleByName(s.name) || 'flex'
const substantial = (role:DishRole,tags:string[]) => role==='main'||lower(tags).includes('substantial')
const categoryOf=(item:PantryItem)=>{const text=`${item.name} ${item.tags.join(' ')}`.toLowerCase();if(['vegetable','fruit','tomato','pepper','aubergine','eggplant'].some(x=>text.includes(x)))return'vegetables';if(['grain','rice','pasta','bread','potato','starch','polenta'].some(x=>text.includes(x)))return'grains';if(['herb','aromatic','mint','parsley','cilantro','onion','garlic'].some(x=>text.includes(x)))return'herbs';if(GROUPS.protein.some(x=>text.includes(x)))return'proteins';return'sauces'}

export function dinerDishFit(diner:TasteProfile,dish:Pick<Signature,'name'|'tags'|'contains_allergens'|'novelty_score'>,guestCount:number):Fit {
  const tags=lower(dish.tags), allergens=lower(dish.contains_allergens), restrictions=lower(diner.dietary), avoids=lower(diner.avoid)
  const allergyConflict=[...allergens,...tags].some(x=>ALLERGY_WORDS.has(x)&&(avoids.includes(x)||restrictions.includes(x)))
  const dietConflict=restrictions.filter(x=>HARD_DIETS.has(x)).some(d=>d==='vegan'?!tags.includes('vegan'):d==='vegetarian'?!tags.some(x=>['veg','vegetarian','vegan'].includes(x)):d==='no pork'?tags.includes('pork'):d==='no dairy'?tags.includes('dairy'):d==='gluten-free'?tags.includes('gluten'):false)
  const eligibility:0|1=(dietConflict||(allergyConflict&&guestCount<RECOMMENDATION_CONFIG.allergy.largeGroupCutoff))?0:1
  if (allergyConflict&&guestCount>=RECOMMENDATION_CONFIG.allergy.largeGroupCutoff) return {eligibility:0,protein:0,flavor:0,adventurousness:0,q:0}
  const proteins=lower(diner.proteinPreferences??[]), dishProteins=group(tags,dish.name).protein,noPreference=!proteins.length||proteins.includes('no_preference')
  const protein=noPreference?.65:dishProteins.some(x=>proteins.some(p=>p.includes(x)||x.includes(p)))?1:dishProteins.length?.3:.65
  const sensory=lower(diner.flavorPreference),dimensions=group(tags,dish.name),dishSensory=Array.from(new Set([...dimensions.flavor,...dimensions.texture,...dimensions.technique,...dimensions.richness]))
  const flavor=sensory.length===0?.5:dishSensory.length?clamp(dishSensory.filter(x=>sensory.includes(x)).length/sensory.length):.5
  const novelty=dish.novelty_score??(tags.includes('very_unusual')?.95:tags.includes('adventurous')?.75:tags.includes('uncommon')?.5:tags.includes('familiar')?.25:null)
  const adventurousness=novelty===null?.5:1-Math.abs((diner.adventurousness??50)/100-novelty)
  return {eligibility,protein,flavor,adventurousness,q:eligibility*clamp(.45*protein+.35*flavor+.2*adventurousness)}
}

function similarity(a:Signature,b:Signature){const A=group(a.tags,a.name),B=group(b.tags,b.name);return .3*jaccard(A.flavor,B.flavor)+.2*jaccard(A.texture,B.texture)+.15*jaccard(A.technique,B.technique)+.15*jaccard(A.protein,B.protein)+.1*jaccard(A.temperature,B.temperature)+.1*jaccard(A.richness,B.richness)}

export function buildRecommendationPlan(guests:TasteProfile[],signatures:Signature[],pantry:PantryItem[],locked:Signature[]=[]):RecommendationPlan{
  const G=guests.length,N=Math.max(calculateTargetDishCount(G),locked.length),prefTarget=requiredSatisfyingDishCount(N),subTarget=requiredSubstantialDishCount(N),blue=roleBlueprint(N),ceil=roleCeilings(N)
  const selected:ScoredSignature[]=[], remaining=signatures.filter(s=>!locked.some(l=>l.id===s.id)), counts:Record<string,number>={starter:0,main:0,side:0,dessert:0,flex:0},candidateLog=new Map<string,SignatureCandidateDiagnostic>()
  const residual=():Residual[]=>guests.map((g,i)=>{const sat=selected.filter(s=>s.fits[i]?.q>=.6).length,sub=selected.filter(s=>s.fits[i]?.eligibility&&substantial(s.role,s.signature.tags)).length;return{name:g.name,satisfying:sat,substantial:sub,value:Math.max(0,1-sat/prefTarget,1-sub/subTarget)}})
  const add=(s:Signature)=>{const fits=guests.map(g=>dinerDishFit(g,s,G));const role=roleOf(s);selected.push({signature:s,role,score:1,base:1,underserved:1,diversity:.5,fits});counts[role]++;candidateLog.set(s.id,{name:s.name,role,T_d:1,S_d:1,R_d:1,U_d:1,B_d:1,RoleNeed:1,D_d:.5,M_d:1,baseScore:1,dynamicScore:1,selected:true,reason:'locked dish already fills a menu position'})}
  locked.forEach(add)
  while(selected.length<N&&remaining.length){const rs=residual(),sumR=rs.reduce((a,r)=>a+r.value,0);const candidates=remaining.map(signature=>{const role=roleOf(signature),fits=guests.map(g=>dinerDishFit(g,signature,G)),avg=(f:(x:Fit)=>number)=>G?fits.reduce((a,x)=>a+f(x),0)/G:0,T=avg(f=>f.q),S=avg(f=>f.q>=.6?1:0),R=avg(f=>f.eligibility),U=sumR?fits.reduce((a,f,i)=>a+rs[i].value*(f.q>=.6?1:0),0)/sumR:0,B=.45*T+.25*S+.15*R+.15*U,roleNeed=role==='flex'?.5:counts[role]<((blue as Record<string,number>)[role]??0)?1:.5,diversity=selected.length?1-Math.max(...selected.map(x=>similarity(signature,x.signature))):.5,score=.75*B+.15*roleNeed+.1*diversity,allergyBlocked=G<8&&fits.some(f=>!f.eligibility),roleBlocked=role!=='flex'&&counts[role]>=(ceil as Record<string,number>)[role],passes=score>=.7||(score>=.58&&U>=.6&&substantial(role,signature.tags));candidateLog.set(signature.id,{name:signature.name,role,T_d:T,S_d:S,R_d:R,U_d:U,B_d:B,RoleNeed:roleNeed,D_d:diversity,M_d:score,baseScore:B,dynamicScore:score,selected:false,reason:allergyBlocked?'excluded before selection: allergy or hard-diet conflict below 8 guests':roleBlocked?`rejected: ${role} role ceiling reached`:passes?'eligible but lower marginal gain than selected candidate':`rejected: dynamic score ${score.toFixed(3)} did not meet strong/conditional threshold`});return allergyBlocked||roleBlocked?null:{signature,role,score,base:B,underserved:U,diversity,fits}}).filter(Boolean) as ScoredSignature[]
    candidates.sort((a,b)=>b.score-a.score);const best=candidates.find(c=>c.score>=.7||(c.score>=.58&&c.underserved>=.6&&substantial(c.role,c.signature.tags)));if(!best)break;selected.push(best);counts[best.role]++;candidateLog.set(best.signature.id,{...candidateLog.get(best.signature.id)!,selected:true,reason:`selected by sequential marginal gain at position ${selected.length}`});remaining.splice(remaining.findIndex(s=>s.id===best.signature.id),1)
  }
  const residuals=residual(),under=residuals.filter(r=>r.value>0),missing=N-selected.length,roles=Object.entries(blue).flatMap(([r,n])=>Array(Math.max(0,(n??0)-(counts[r]??0))).fill(r as DishRole));while(roles.length<missing)roles.push('flex')
  const flavors=Array.from(new Set(guests.flatMap((g,i)=>residuals[i].value>0?lower(g.flavorPreference):[]))),proteins=Array.from(new Set(guests.flatMap((g,i)=>residuals[i].value>0?lower(g.proteinPreferences??[]):[])))
  const constraints=Array.from(new Set(guests.flatMap(g=>g.dietary.concat(g.avoid))))
  const needs=residuals.map((r,dinerIndex)=>({dinerIndex,satisfying:Math.max(0,prefTarget-r.satisfying),substantial:Math.max(0,subTarget-r.substantial)})),substantialGapCount=roles.filter(r=>r==='main'||r==='side').length,infeasibleDinerIndexes=needs.filter(n=>n.satisfying>missing||n.substantial>substantialGapCount).map(n=>n.dinerIndex),allocated:GapDinerTarget[][]=Array.from({length:missing},()=>[])
  const targetFor=(dinerIndex:number,substantialNeed:boolean):GapDinerTarget=>{const g=guests[dinerIndex];return{dinerIndex,needsSatisfyingDish:true,needsSubstantialSafeDish:substantialNeed,proteinNeed:lower(g.proteinPreferences??[]),flavorNeed:lower(g.flavorPreference??[]),dietaryConstraints:Array.from(new Set([...g.dietary,...g.avoid]))}}
  const conflict=(a:GapDinerTarget,b:GapDinerTarget)=>{const aVeg=a.dietaryConstraints.some(x=>['vegetarian','vegan'].includes(x.toLowerCase())),bVeg=b.dietaryConstraints.some(x=>['vegetarian','vegan'].includes(x.toLowerCase())),animals=new Set(['beef_lamb','beef','lamb','chicken','fish','shellfish','pork','duck','turkey']);return(aVeg&&b.proteinNeed.some(x=>animals.has(x)))||(bVeg&&a.proteinNeed.some(x=>animals.has(x)))}
  for(const need of [...needs].sort((a,b)=>b.substantial-a.substantial||b.satisfying-a.satisfying)){const chosen=new Set<number>(),pick=(substantialNeed:boolean)=>{const target=targetFor(need.dinerIndex,substantialNeed),candidates=Array.from({length:missing},(_,i)=>i).filter(i=>!chosen.has(i)&&(!substantialNeed||(roles[i]==='main'||roles[i]==='side'))).sort((a,b)=>{const ca=allocated[a].filter(x=>conflict(target,x)).length,cb=allocated[b].filter(x=>conflict(target,x)).length;return ca-cb||allocated[a].length-allocated[b].length||a-b}),index=candidates[0];if(index!==undefined){allocated[index].push(target);chosen.add(index)}};for(let i=0;i<need.substantial;i++)pick(true);for(let i=need.substantial;i<need.satisfying;i++)pick(false)}
  const gaps=Array.from({length:missing},(_,i)=>{const targetDiners=allocated[i];return{gapIndex:i,requestedRole:roles[i]??'flex',substantialRequired:targetDiners.some(t=>t.needsSubstantialSafeDish),targetDiners,underservedDinerSummary:targetDiners.map(t=>`Diner ${t.dinerIndex}: needs satisfying${t.needsSubstantialSafeDish?' and substantial':''}`),dietaryConstraints:Array.from(new Set(targetDiners.flatMap(t=>t.dietaryConstraints))),proteinDirections:Array.from(new Set(targetDiners.flatMap(t=>t.proteinNeed))),flavorDirections:Array.from(new Set(targetDiners.flatMap(t=>t.flavorNeed))),avoidRepetition:selected.map(s=>s.signature.name)}})
  const cap=ingredientContextCeiling(missing), scored=pantry.map(item=>{const tags=lower(item.tags),gapFit=gaps.some(g=>g.requestedRole==='dessert'?tags.some(t=>['fruit','dairy','sweet'].includes(t)):g.substantialRequired?tags.some(t=>GROUPS.protein.includes(t)):true)?1:.2;const dinerFit=tags.some(t=>proteins.concat(flavors).includes(t))?1:.5;const relevance=.4*gapFit+.3*dinerFit+.2*.7+.1*.7;return{item,category:categoryOf(item),relevance,redundancy:0,mmr:0}}),thresholded=scored.filter(x=>x.relevance>=.55)
  const limits:Record<string,number>={proteins:Math.min(7,2*missing+3),vegetables:Math.min(8,2*missing+4),grains:Math.min(5,missing+2),herbs:Math.min(6,missing+3),sauces:Math.min(6,missing+3)},seen:Record<string,number>={};const diagnostics=thresholded.sort((a,b)=>b.relevance-a.relevance).filter(x=>{seen[x.category]=(seen[x.category]??0)+1;return seen[x.category]<=limits[x.category]})
  const afterCategoryCeilings=diagnostics.length,ingredients:IngredientDiagnostic[]=[];while(ingredients.length<cap&&diagnostics.length){for(const d of diagnostics){d.redundancy=ingredients.length?Math.max(...ingredients.map(s=>jaccard(lower(d.item.tags),lower(s.item.tags)))):0;d.mmr=.8*d.relevance-.2*d.redundancy}diagnostics.sort((a,b)=>b.mmr-a.mmr);ingredients.push(diagnostics.shift()!)}
  const breakdown:Record<string,number>={};ingredients.forEach(x=>breakdown[x.category]=(breakdown[x.category]??0)+1)
  remaining.forEach(signature=>{if(!candidateLog.has(signature.id))candidateLog.set(signature.id,{name:signature.name,role:roleOf(signature),T_d:0,S_d:0,R_d:0,U_d:0,B_d:0,RoleNeed:0,D_d:0,M_d:0,baseScore:0,dynamicScore:0,selected:false,reason:'not evaluated: menu positions already filled'})})
  return{guestCount:G,targetDishCount:N,selected,residuals,gaps,ingredients,contextCeiling:cap,retrievalDiagnostics:{beforeThreshold:scored.length,afterThreshold:thresholded.length,afterCategoryCeilings,afterMmr:ingredients.length,categoryBreakdown:breakdown},signatureCandidates:signatures.map(s=>candidateLog.get(s.id)!),lockedCount:locked.length,infeasibleDinerIndexes,insufficientData:selected.every(s=>s.score<.7)&&ingredients.length<4}
}
