import type { TasteProfile } from '@/lib/intel'
import type { PantryItem, Signature } from '@/lib/menu'
import { RECOMMENDATION_CONFIG, type DishRole } from './config'
import { dinerDishFit } from './pipeline'
import type { GeneratedDishMetadata } from './proposal'
import { purchaseClass, requiredSatisfyingDishCount, requiredSubstantialDishCount, roleCeilings } from './planning'

export type FinalDish={name:string;role:DishRole;origin:'signature'|'signature-refinement'|'generated'|'host';baseSignatureName?:string;usedAvailableIngredients:string[];missingIngredients:{name:string;importance:'core'|'supporting'|'optional'}[];scoringMetadata?:GeneratedDishMetadata;locked?:boolean;sourceId?:string|null;componentIds?:string[]}
export type ValidationCode='schema'|'dish-count'|'signature-lineage'|'pantry-lineage'|'missing-classification'|'allergy'|'dietary'|'role-ceiling'|'diner-satisfaction'|'substantial-coverage'|'menu-average'|'duplicate'|'purchase-limit'|'trusted-id'
export type ValidationIssue={order:number;code:ValidationCode;severity:'error'|'repair'|'warning';message:string;dishIndex?:number;dinerIndex?:number}
export type ValidationResult={valid:boolean;issues:ValidationIssue[];normalized:FinalDish[];menuAverage:number;repairable:boolean}
const ORDER:Record<ValidationCode,number>={'schema':1,'dish-count':2,'signature-lineage':3,'pantry-lineage':4,'missing-classification':5,'allergy':6,'dietary':7,'role-ceiling':8,'diner-satisfaction':9,'substantial-coverage':10,'menu-average':11,'duplicate':12,'purchase-limit':13,'trusted-id':14}
const ALLERGY_WORDS=new Set(['nuts','shellfish','dairy','eggs','gluten','soy','sesame','mustard','celery','sulfites','lupin','molluscs'])
const add=(issues:ValidationIssue[],code:ValidationCode,severity:ValidationIssue['severity'],message:string,extra:Partial<ValidationIssue>={})=>issues.push({order:ORDER[code],code,severity,message,...extra})
const norm=(s:string)=>s.trim().toLowerCase().replace(/[^a-z0-9]+/g,' ')
const planningTerms=(values:string[])=>values.flatMap(value=>{const v=norm(value);if(v==='beef lamb')return['beef','lamb'];if(v==='grain pasta')return['grain','pasta'];if(v==='umami')return['savory'];if(v==='plain clean')return['fresh','light'];if(v==='saucy')return['rich'];if(v==='bright sour')return['bright','tangy'];if(v==='sweet savoury')return['sweet','savory'];if(v==='herby')return['fresh'];return v.split(' ')}).filter(Boolean)

export function validateFinalMenu(input:{dishes:FinalDish[];target:number;guests:TasteProfile[];signatures:Signature[];pantry:PantryItem[]}):ValidationResult{
  const {dishes,target,guests,signatures,pantry}=input,issues:ValidationIssue[]=[],signatureNames=new Map(signatures.map(s=>[s.name,s])),pantryNames=new Map(pantry.map(p=>[p.name,p]))
  if(!Array.isArray(dishes)||dishes.some(d=>!d?.name||!d.role||!Array.isArray(d.usedAvailableIngredients)||!Array.isArray(d.missingIngredients)))add(issues,'schema','error','Malformed final menu')
  if(dishes.length!==target)add(issues,'dish-count','error',`Expected ${target} dishes, received ${dishes.length}`)
  dishes.forEach((d,i)=>{if(d.origin==='signature'||d.origin==='signature-refinement'){const base=d.baseSignatureName??d.name;if(!signatureNames.has(base))add(issues,'signature-lineage','error',`Unknown signature ${base}`,{dishIndex:i})}for(const name of d.usedAvailableIngredients)if(!pantryNames.has(name))add(issues,'pantry-lineage','error',`Unavailable pantry ingredient ${name}`,{dishIndex:i});const declared=new Set(d.missingIngredients.map(x=>norm(x.name)));for(const name of d.usedAvailableIngredients)if(!pantryNames.has(name)&&!declared.has(norm(name)))add(issues,'missing-classification','error',`Unclassified missing ingredient ${name}`,{dishIndex:i})})
  const safety=dishes.map(d=>{const sig=d.origin.startsWith('signature')?signatureNames.get(d.baseSignatureName??d.name):undefined;const items=d.usedAvailableIngredients.map(n=>pantryNames.get(n)).filter(Boolean) as PantryItem[];const m=d.scoringMetadata;return{name:d.name,tags:sig?.tags??Array.from(new Set(m?[d.role,...m.proteinBase,...m.flavors,...m.textures,...m.techniques,...m.temperature,...m.richness,...m.dietary]:items.flatMap(x=>x.tags))),contains_allergens:sig?.contains_allergens??(m?.allergens??items.flatMap(x=>x.contains_allergens)),novelty_score:sig?.novelty_score??m?.noveltyScore??null,is_substantial:sig?.is_substantial??m?.substantial??null}})
  const fitGuests=guests.map(g=>({...g,flavorPreference:planningTerms(g.flavorPreference??[])}))
  const fits=safety.map(d=>fitGuests.map(g=>dinerDishFit(g,d,guests.length)))
  fits.forEach((row,di)=>row.forEach((f,gi)=>{if(!f.eligibility){const guest=guests[gi],terms=[...safety[di].tags,...safety[di].contains_allergens].map(norm),allergy=terms.some(x=>ALLERGY_WORDS.has(x)&&guest.avoid.map(norm).includes(x));if(allergy&&guests.length<RECOMMENDATION_CONFIG.allergy.largeGroupCutoff)add(issues,'allergy','error',`${dishes[di].name} conflicts with diner constraints`,{dishIndex:di,dinerIndex:gi})}}))
  const ceilings=roleCeilings(target);for(const role of ['starter','main','side','dessert'] as const){const indexes=dishes.map((d,i)=>d.role===role?i:-1).filter(i=>i>=0);if(indexes.length>ceilings[role])indexes.slice(ceilings[role]).forEach(i=>add(issues,'role-ceiling','repair',`${role} ceiling exceeded`,{dishIndex:i}))}
  const score=(di:number,gi:number)=>{const guest=guests[gi],neutral=!(guest.proteinPreferences?.length)&&!(guest.flavorPreference?.length);return neutral?(fits[di][gi].eligibility?.65:0):fits[di][gi].q}
  const pref=requiredSatisfyingDishCount(target),sub=requiredSubstantialDishCount(target);guests.forEach((_,gi)=>{const satisfying=fits.filter((_,di)=>score(di,gi)>=RECOMMENDATION_CONFIG.satisfaction.dishThreshold).length,substantial=fits.filter((r,di)=>r[gi]?.eligibility&&(dishes[di].role==='main'||dishes[di].role==='side')).length;if(satisfying<pref)add(issues,'diner-satisfaction','repair',`Diner needs ${pref-satisfying} more satisfying dishes`,{dinerIndex:gi});if(substantial<sub)add(issues,'substantial-coverage','repair',`Diner needs ${sub-substantial} more substantial dishes`,{dinerIndex:gi})})
  const values=fits.flatMap((_,di)=>guests.map((__,gi)=>score(di,gi))),menuAverage=values.length?values.reduce((a,b)=>a+b,0)/values.length:0;if(menuAverage<.5)add(issues,'menu-average','repair',`Menu average ${menuAverage.toFixed(2)}`);else if(menuAverage<.65)add(issues,'menu-average','warning',`Menu average ${menuAverage.toFixed(2)}`)
  const seen=new Map<string,number>();dishes.forEach((d,i)=>{const key=norm(d.name);if(seen.has(key))add(issues,'duplicate','repair',`Duplicate dish ${d.name}`,{dishIndex:i});else seen.set(key,i)})
  const missing=new Set<string>();dishes.forEach((d,i)=>{for(const m of d.missingIngredients)missing.add(norm(m.name));if(purchaseClass(d.missingIngredients)==='repair-required')add(issues,'purchase-limit','repair',`Purchase limit exceeded for ${d.name}`,{dishIndex:i})});if(missing.size>4)add(issues,'purchase-limit','warning','More than four unique missing ingredients require approval')
  const normalized=dishes.map((d,i)=>{const sig=signatureNames.get(d.baseSignatureName??d.name),ids=d.usedAvailableIngredients.map(n=>pantryNames.get(n)?.id).filter(Boolean) as string[];if((d.origin.startsWith('signature')&&!sig)||ids.length!==d.usedAvailableIngredients.length)add(issues,'trusted-id','error',`Trusted lineage normalization failed`,{dishIndex:i});return{...d,sourceId:sig?.id??null,componentIds:ids}})
  issues.sort((a,b)=>a.order-b.order);return{valid:!issues.some(i=>i.severity!=='warning'),issues,normalized,menuAverage,repairable:issues.some(i=>i.severity!=='warning'&&i.code!=='schema'&&i.code!=='trusted-id')}
}

const REPAIR_PRIORITY:Partial<Record<ValidationCode,number>>={allergy:1,dietary:1,'signature-lineage':2,'pantry-lineage':2,'missing-classification':2,'dish-count':3,'substantial-coverage':4,'diner-satisfaction':5,'role-ceiling':6,duplicate:7,'menu-average':8,'purchase-limit':9}
const deficit=(issue:ValidationIssue)=>Number(issue.message.match(/needs (\d+) more/)?.[1]??0)
export function chooseRepairIssue(issues:ValidationIssue[]):ValidationIssue|undefined{return issues.filter(i=>i.severity!=='warning'&&REPAIR_PRIORITY[i.code]!==undefined).sort((a,b)=>{const priority=(REPAIR_PRIORITY[a.code]??99)-(REPAIR_PRIORITY[b.code]??99);if(priority)return priority;if(a.code==='diner-satisfaction'||a.code==='substantial-coverage')return deficit(b)-deficit(a);return 0})[0]}
export function chooseReplacementDishIndex(dishes:FinalDish[],targetScore:(dish:FinalDish)=>number,tableScore:(dish:FinalDish)=>number):number{return dishes.map((dish,index)=>({dish,index,target:targetScore(dish),table:tableScore(dish)})).filter(x=>!x.dish.locked).sort((a,b)=>(a.target-b.target)||(a.table-b.table))[0]?.index??-1}

// Safety/schema violations only -- 'repair'-severity issues (diner-satisfaction,
// substantial-coverage, menu-average, role-ceiling, duplicate) that survive the
// repair budget are optimization shortfalls, never a reason to discard an
// otherwise-safe menu.
export const hasBlockingIssues=(issues:ValidationIssue[])=>issues.some(i=>i.severity==='error')

export async function repairWithLimit(initial:FinalDish[],validate:(d:FinalDish[])=>ValidationResult,replaceOne:(d:FinalDish[],issue:ValidationIssue,attempt:number)=>Promise<{index:number;dish:FinalDish}|null>,maximumAttempts=2){let dishes=initial,result=validate(dishes),attempts=0;while(!result.valid&&result.repairable&&attempts<Math.min(2,maximumAttempts)){const issue=chooseRepairIssue(result.issues);if(!issue)break;const replacement=await replaceOne(dishes,issue,attempts+1);attempts++;if(!replacement||replacement.index<0||replacement.index>=dishes.length||dishes[replacement.index]?.locked)continue;dishes=dishes.map((d,i)=>i===replacement.index?replacement.dish:d);result=validate(dishes)}return{dishes,result,attempts,warning:result.valid?undefined:`Automatic repair stopped after ${attempts} attempt${attempts===1?'':'s'}.`}}
