import { NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { inferIngredientAllergens, type RecipeIngredient, type RecipeSource } from '@/lib/recipes'

async function authorizedMenu(eventId:string,userId:string){const db=createClient(),{data:event}=await db.from('events').select('host_id').eq('id',eventId).maybeSingle();if(!event||event.host_id!==userId)return null;const{data:menu}=await db.from('menus').select('id').eq('event_id',eventId).maybeSingle();return menu?.id??null}

export async function GET(req:Request){const url=new URL(req.url),eventId=url.searchParams.get('eventId'),userId=url.searchParams.get('userId');if(!eventId||!userId)return NextResponse.json({error:'Missing identifiers'},{status:400});const menuId=await authorizedMenu(eventId,userId);if(!menuId)return NextResponse.json({error:'Forbidden or menu not found'},{status:403});const db=createClient(),{data:courses,error}=await db.from('menu_courses').select('id,slot,dish_name,dish_origin,source,component_ids,sort_order,recipes(id,menu_course_id,source,base_servings,instructions,recipe_ingredients(id,ingredient_name,quantity_amount,quantity_unit,tags,contains_allergens,sort_order,pantry_item_id))').eq('menu_id',menuId).order('sort_order');if(error)return NextResponse.json({error:'Failed to load recipes'},{status:500});return NextResponse.json({courses})}

export async function PUT(req:Request){let body:{eventId?:unknown;userId?:unknown;courseId?:unknown;source?:unknown;baseServings?:unknown;instructions?:unknown;ingredients?:unknown};try{body=await req.json()}catch{return NextResponse.json({error:'Invalid JSON'},{status:400})}if(typeof body.eventId!=='string'||typeof body.userId!=='string'||typeof body.courseId!=='string'||!['host_provided','ai_generated'].includes(String(body.source))||!Number.isInteger(body.baseServings)||Number(body.baseServings)<=0||typeof body.instructions!=='string'||!Array.isArray(body.ingredients))return NextResponse.json({error:'Invalid recipe'},{status:400});const menuId=await authorizedMenu(body.eventId,body.userId);if(!menuId)return NextResponse.json({error:'Forbidden or menu not found'},{status:403});const db=createClient(),{data:course}=await db.from('menu_courses').select('id').eq('id',body.courseId).eq('menu_id',menuId).maybeSingle();if(!course)return NextResponse.json({error:'Course not found'},{status:404});const ingredients=(body.ingredients as Partial<RecipeIngredient>[]).map((item,index)=>({ingredient_name:String(item.ingredient_name??'').trim(),quantity_amount:Number(item.quantity_amount),quantity_unit:String(item.quantity_unit??'').trim(),tags:Array.isArray(item.tags)?item.tags.filter((x):x is string=>typeof x==='string'):[],contains_allergens:Array.from(new Set([...(Array.isArray(item.contains_allergens)?item.contains_allergens.filter((x):x is string=>typeof x==='string'):[]),...inferIngredientAllergens(String(item.ingredient_name??''))])),sort_order:index,pantry_item_id:typeof item.pantry_item_id==='string'?item.pantry_item_id:null}));if(!ingredients.length||ingredients.some(x=>!x.ingredient_name||!Number.isFinite(x.quantity_amount)||x.quantity_amount<0||!x.quantity_unit))return NextResponse.json({error:'Invalid ingredients'},{status:400});const{data:recipe,error}=await db.from('recipes').upsert({menu_course_id:body.courseId,source:body.source as RecipeSource,base_servings:body.baseServings,instructions:body.instructions.trim(),updated_at:new Date().toISOString()},{onConflict:'menu_course_id'}).select('id,menu_course_id,source,base_servings,instructions').single();if(error||!recipe)return NextResponse.json({error:'Failed to save recipe'},{status:500});await db.from('recipe_ingredients').delete().eq('recipe_id',recipe.id);const{data:saved,error:ingredientError}=await db.from('recipe_ingredients').insert(ingredients.map(x=>({...x,recipe_id:recipe.id}))).select('id,ingredient_name,quantity_amount,quantity_unit,tags,contains_allergens,sort_order,pantry_item_id');if(ingredientError)return NextResponse.json({error:'Failed to save ingredients'},{status:500});return NextResponse.json({recipe:{...recipe,ingredients:saved??[]}})}
