import {render,screen} from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import {useRouter} from 'next/navigation'
import {createClient} from '@/lib/supabase/client'
import EventsPage from '@/app/design-preview/events/page'
import EventPage from '@/app/design-preview/events/demo/page'
import InvitePage from '@/app/design-preview/invite/page'
import MissingOutPage from '@/app/design-preview/invite/missing-out/page'
import ProfilePage from '@/app/design-preview/profile/page'
import HostPage from '@/app/design-preview/host/page'
import MenuPage from '@/app/design-preview/menu/page'
import CuratedMenusPage from '@/app/design-preview/curated-menus/page'
import CuratedMenuDemoPage from '@/app/design-preview/curated-menus/demo/page'
import MyKitchenPage from '@/app/design-preview/my-kitchen/page'
import GalleryPage from '@/app/design-preview/page'
import {EventDetailPreview} from '@/components/sofra-v2/EventDetailPreview'
import {MyKitchenPreview} from '@/components/sofra-v2/MyKitchenPreview'
import {CuratedMenusPreview} from '@/components/sofra-v2/CuratedMenusPreview'

jest.mock('@/lib/supabase/client')
jest.mock('next/navigation',()=>({useRouter:jest.fn()}))
const push=jest.fn()
beforeEach(()=>{push.mockClear();sessionStorage.clear();Object.defineProperty(URL,'revokeObjectURL',{configurable:true,value:jest.fn()});(createClient as jest.Mock).mockClear();(useRouter as jest.Mock).mockReturnValue({push})})

it('renders Sofras without an avatar, cart, or dishes and uses shared navigation',()=>{const {container}=render(<EventsPage/>);expect(screen.getByText('YOUR SOFRAS')).toBeInTheDocument();expect(container.querySelector('.sv2-avatar')).toBeNull();for(const label of ['SOFRAS','HOST','PROFILE'])expect(screen.getByRole('link',{name:label})).toBeInTheDocument();expect(screen.queryByText('HOST (+)')).not.toBeInTheDocument()})
it('shows guest details with EDIT RSVP and Shared Album but no host controls',()=>{render(<EventPage/>);expect(screen.getByRole('link',{name:'EDIT RSVP'})).toBeInTheDocument();expect(screen.getByRole('heading',{name:'Shared Album'})).toBeInTheDocument();expect(screen.queryByRole('button',{name:'EDIT EVENT'})).not.toBeInTheDocument();expect(screen.queryByRole('link',{name:'INVENTORY'})).not.toBeInTheDocument()})
it('routes accepted and tentative RSVPs to Preferences and decline to Missing Out',async()=>{const user=userEvent.setup();render(<InvitePage/>);await user.click(screen.getByRole('button',{name:'SAVE ME A SEAT'}));expect(sessionStorage.getItem('sofra-preview-rsvp')).toBe('going');expect(push).toHaveBeenCalledWith('/design-preview/preferences');await user.click(screen.getByRole('button',{name:"I'LL THINK ABOUT IT"}));expect(sessionStorage.getItem('sofra-preview-rsvp')).toBe('tentative');await user.click(screen.getByRole('button',{name:'MAYBE NEXT TIME'}));expect(push).toHaveBeenCalledWith('/design-preview/invite/missing-out')})
it('renders the missing-out destination',()=>{render(<MissingOutPage/>);expect(screen.getByText("The plates will try not to take it personally.")).toBeInTheDocument()})
it('keeps appearance controls only on Profile and provides preview logout',()=>{const routes=[<EventsPage key="events"/>,<EventPage key="event"/>,<InvitePage key="invite"/>,<HostPage key="host"/>,<MenuPage key="menu"/>,<CuratedMenusPage key="curated"/>,<MyKitchenPage key="kitchen"/>];for(const page of routes){const view=render(page);expect(screen.queryByRole('group',{name:'Preview appearance'})).not.toBeInTheDocument();view.unmount()}render(<ProfilePage/>);expect(screen.getByRole('group',{name:'Preview appearance'})).toBeInTheDocument();expect(screen.getByRole('button',{name:'LOG OUT'})).toBeInTheDocument()})
it('renders curated menus and kitchen as text-only local collections',()=>{const index=render(<CuratedMenusPage/>);expect(screen.getByRole('heading',{name:'Curated Menus'})).toBeInTheDocument();index.unmount();const detail=render(<CuratedMenuDemoPage/>);expect(screen.getByText('Heirloom Tomato & Labneh')).toBeInTheDocument();expect(detail.container.querySelector('.sv2-menu-image-placeholder')).toBeNull();expect(screen.queryByRole('button',{name:/explore menu/i})).not.toBeInTheDocument();detail.unmount();render(<MyKitchenPage/>);expect(screen.getByRole('heading',{name:'My Kitchen'})).toBeInTheDocument();expect(screen.getByRole('heading',{name:'SIGNATURE DISHES'})).toBeInTheDocument();expect(createClient).not.toHaveBeenCalled()})
it('renders the host form and every requested gallery route',()=>{const host=render(<HostPage/>);expect(screen.getByRole('heading',{name:'Create a Sofra'})).toBeInTheDocument();host.unmount();render(<GalleryPage/>);for(const route of ['/design-preview/welcome','/design-preview/signup','/design-preview/name','/design-preview/preferences','/design-preview/events','/design-preview/events/demo?role=guest','/design-preview/host','/design-preview/invite','/design-preview/invite/missing-out','/design-preview/curated-menus','/design-preview/curated-menus/demo','/design-preview/my-kitchen','/design-preview/profile'])expect(screen.getByText(route)).toBeInTheDocument()})
it('uses INVITED, WENT, and HOSTING tabs',()=>{render(<EventsPage/>);for(const tab of ['INVITED','WENT','HOSTING'])expect(screen.getByRole('button',{name:tab})).toBeInTheDocument()})
it('keeps host event controls distinct from RSVP controls',()=>{render(<EventDetailPreview role="host"/>);for(const name of ['EDIT EVENT','MANAGE GUESTS','COPY INVITE LINK','SHARE ON WHATSAPP','VIEW PREFERENCE SUMMARY'])expect(screen.getByRole('button',{name})).toBeInTheDocument();expect(screen.getByRole('link',{name:'INVENTORY'})).toBeInTheDocument();expect(screen.getByRole('link',{name:'CURATED MENU'})).toBeInTheDocument();expect(screen.queryByText('EDIT RSVP')).not.toBeInTheDocument()})
it('toggles canonical inventory chips and manages custom tags locally',async()=>{const user=userEvent.setup();render(<MyKitchenPreview eventContext/>);const chicken=screen.getByRole('button',{name:'Chicken thighs'});await user.click(chicken);expect(chicken).toHaveAttribute('aria-pressed','false');const input=screen.getByLabelText('Add custom pantry item');await user.type(input,'  Aleppo pepper  {enter}');expect(screen.getByText('Aleppo pepper')).toBeInTheDocument();expect(screen.getByRole('button',{name:'Remove Aleppo pepper'})).toBeInTheDocument();await user.type(input,'aleppo pepper{enter}');expect(screen.getAllByText('Aleppo pepper')).toHaveLength(1);expect(screen.getByRole('button',{name:'UPDATE INVENTORY'})).toBeInTheDocument()})
it('opens menu export customization without cart, theme, or images',async()=>{const user=userEvent.setup();const {container}=render(<CuratedMenusPreview detail/>);await user.click(screen.getByRole('button',{name:'EXPORT MENU'}));expect(screen.getByRole('region',{name:'Menu export customization'})).toBeInTheDocument();expect(screen.getByRole('button',{name:'Portrait'})).toBeInTheDocument();expect(screen.getByRole('button',{name:'PDF-style preview'})).toBeInTheDocument();expect(screen.queryByText('Cart')).not.toBeInTheDocument();expect(container.querySelector('.sv2-menu-image-placeholder')).toBeNull()})
it('locks invite identities and provides the reveal message before RSVP',()=>{render(<InvitePage/>);expect(screen.getByText("WHO'S AROUND THE SOFRA")).toBeInTheDocument();expect(screen.getByText('RSVP to meet the rest of the table.')).toBeInTheDocument();expect(screen.getAllByLabelText('Guest identity locked').length).toBeGreaterThan(0)})
it('previews a selected profile photo locally',async()=>{const user=userEvent.setup();Object.defineProperty(URL,'createObjectURL',{configurable:true,value:jest.fn(()=> 'blob:profile')});Object.defineProperty(URL,'revokeObjectURL',{configurable:true,value:jest.fn()});render(<ProfilePage/>);const input=screen.getByLabelText('Choose a profile photo');await user.upload(input,new File(['photo'],'alia.png',{type:'image/png'}));expect(screen.getByAltText('Selected local profile preview')).toHaveAttribute('src','blob:profile');expect(createClient).not.toHaveBeenCalled()})
