import { parseMenuProposal } from '@/lib/recommendation/proposal'
import type { MenuCreationBrief } from '@/lib/recommendation/brief'

const brief:MenuCreationBrief={event:{guestCount:4,targetDishCount:4,missingDishCount:1},selectedSignatures:[{name:'Chicken',role:'main',mayBeRefined:false}],gaps:[{gapIndex:0,requestedRole:'side',substantialRequired:false,targetDinerCount:1,targetDiners:[{dinerIndex:2,needsSubstantialSafeDish:false,proteinNeed:['vegetable'],sensoryNeed:['fresh'],dietaryConstraints:[]}],culinaryGoal:'Fresh side',underservedNeed:[],proteinDirections:['vegetable'],flavorDirections:['fresh'],avoid:['Chicken']}],availableIngredientsByCategory:[{category:'vegetables',names:['Tomato']}],constraints:['nuts'],purchaseRules:{maximumMissingPerDish:3,maximumCoreMissingPerDish:1,maximumUniqueMissingAcrossMenu:4}}
const metadata={proteinBase:['vegetable'],flavors:['fresh'],textures:['crispy'],techniques:['raw'],temperature:['cold'],richness:['fresh'],noveltyScore:null,dietary:['vegetarian'],allergens:[],substantial:false}
const valid={signatureRefinements:[],generatedDishes:[{role:'side',finalName:'Tomato salad',usedAvailableIngredients:['Tomato'],missingIngredients:[],reasoning:'Fresh contrast.',metadata}]}

test('strict parser accepts exact M and canonical pantry lineage',()=>expect(parseMenuProposal(valid,brief).ok).toBe(true))
test('strict parser rejects wrong count and invented available ingredients',()=>{const result=parseMenuProposal({...valid,generatedDishes:[...valid.generatedDishes,{...valid.generatedDishes[0],usedAvailableIngredients:['Invented']}]},brief);expect(result.ok).toBe(false);if(!result.ok)expect(result.errors.join(' ')).toMatch(/generated_dish_count_validation|pantry_name_validation/)})
test('strict parser rejects unselected signature lineage',()=>{const result=parseMenuProposal({...valid,signatureRefinements:[{baseSignatureName:'Fish',finalName:'Fish 2',usedAvailableIngredients:[],missingIngredients:[],reasoning:'Refined.'}]},brief);expect(result.ok).toBe(false)})
test('parser restores harmless pantry casing and truncates nonessential reasoning',()=>{const words=Array.from({length:25},(_,i)=>`word${i}`).join(' ');const result=parseMenuProposal({...valid,generatedDishes:[{...valid.generatedDishes[0],usedAvailableIngredients:[' tomato '],reasoning:words}]},brief);expect(result.ok).toBe(true);if(result.ok){expect(result.proposal.generatedDishes[0].usedAvailableIngredients).toEqual(['Tomato']);expect(result.proposal.generatedDishes[0].reasoning.split(' ')).toHaveLength(20)}})
test('generated dishes retain distinct canonical metadata and reject table-union values',()=>{const second={...valid.generatedDishes[0],finalName:'Warm lentils',metadata:{...metadata,proteinBase:['legume'],flavors:['earthy'],textures:['tender'],temperature:['hot']}};const twoBrief={...brief,event:{...brief.event,missingDishCount:2},gaps:[...brief.gaps,{...brief.gaps[0],gapIndex:1}]};const result=parseMenuProposal({...valid,generatedDishes:[valid.generatedDishes[0],second]},twoBrief);expect(result.ok).toBe(true);if(result.ok)expect(result.proposal.generatedDishes[0].metadata).not.toEqual(result.proposal.generatedDishes[1].metadata);expect(parseMenuProposal({...valid,generatedDishes:[{...valid.generatedDishes[0],metadata:{...metadata,flavors:['everything']}}]},brief).ok).toBe(false)})
