import { repairWithLimit, validateFinalMenu, type FinalDish } from '@/lib/recommendation/validator'
import type { TasteProfile } from '@/lib/intel'
const guest:TasteProfile={name:'A',dietary:[],avoid:['nuts'],proteinAnchor:null,proteinPreferences:['chicken'],flavorPreference:['savory'],adventurousness:25}
const sig={id:'s1',name:'Chicken',tags:['main','chicken','savory','familiar'],contains_allergens:[],slot:null}
const dish=(name='Chicken'):FinalDish=>({name,role:'main',origin:'signature',baseSignatureName:'Chicken',usedAvailableIngredients:[],missingIngredients:[]})
test('validator issues are returned in required order',()=>{const result=validateFinalMenu({dishes:[{...dish('Bad'),baseSignatureName:'Missing',usedAvailableIngredients:['Fake']}],target:3,guests:[guest],signatures:[sig],pantry:[]});expect(result.issues.map(i=>i.order)).toEqual([...result.issues.map(i=>i.order)].sort((a,b)=>a-b));expect(result.issues.map(i=>i.code)).toEqual(expect.arrayContaining(['dish-count','signature-lineage','pantry-lineage']))})
test('allergy violation blocks a small-group menu',()=>{const result=validateFinalMenu({dishes:[{...dish(),origin:'generated',usedAvailableIngredients:['Nuts']}],target:1,guests:[guest],signatures:[sig],pantry:[{id:'p',name:'Nuts',tags:['nuts'],contains_allergens:['nuts']}]});expect(result.issues.some(i=>i.code==='allergy'&&i.severity==='error')).toBe(true)})
test('repair replaces one unlocked dish and stops after two attempts',async()=>{const invalid={...dish(),origin:'generated' as const};const validate=(d:FinalDish[])=>({valid:false,issues:[{order:12,code:'duplicate' as const,severity:'repair' as const,message:'duplicate',dishIndex:0}],normalized:d,menuAverage:.5,repairable:true});const result=await repairWithLimit([invalid],validate,async()=>({index:0,dish:{...invalid,name:'replacement'}}));expect(result.attempts).toBe(2);expect(result.warning).toMatch(/2 attempts/)})
test('repair never removes a locked dish',async()=>{const locked={...dish(),locked:true};const validate=(d:FinalDish[])=>({valid:false,issues:[{order:12,code:'duplicate' as const,severity:'repair' as const,message:'duplicate',dishIndex:0}],normalized:d,menuAverage:.5,repairable:true});const result=await repairWithLimit([locked],validate,async()=>({index:0,dish:{...locked,name:'changed'}}));expect(result.dishes[0].name).toBe('Chicken')})
